version: '3'

services:
  minio:
    image: docker.io/bitnami/minio:2022
    privileged: true
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root123456
