#端口号配置
server:
  port: 1266

spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# minio 参数配置
minio:
  ip: http://192.168.99.123:9000
  username: root
  password: root1234
  bucket: "test"


logging:
  level:
    root: info

knife4j:
  # 开启增强配置
  enable: true
  setting:
    # 是否开启动态参数调试功能,默认关闭
    enableDynamicParameter: true
